name: test_encortex
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.8.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - adal==1.2.7
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - alembic==1.4.3
    - antlr4-python3-runtime==4.9.3
    - argcomplete==2.0.0
    - async-timeout==4.0.2
    - attrs==22.2.0
    - azure-common==1.1.28
    - azure-core==1.26.2
    - azure-graphrbac==0.61.1
    - azure-identity==1.7.0
    - azure-keyvault-keys==4.5.1
    - azure-keyvault-secrets==4.4.0
    - azure-mgmt-authorization==2.0.0
    - azure-mgmt-containerregistry==10.0.0
    - azure-mgmt-core==1.3.2
    - azure-mgmt-keyvault==10.1.0
    - azure-mgmt-resource==21.2.1
    - azure-mgmt-storage==20.0.0
    - azure-storage-blob==12.9.0
    - azureml-core==1.44.0
    - azureml-mlflow==1.44.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==4.0.1
    - bokeh==3.0.3
    - cachetools==5.2.1
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - class-registry==2.1.2
    - click==7.1.2
    - cloudpickle==2.2.0
    - colorama==0.4.6
    - contextlib2==21.6.0
    - contourpy==1.0.7
    - cron-descriptor==1.2.31
    - cron-validator==1.0.6
    - cryptography==37.0.4
    - cycler==0.11.0
    - dask==2022.8.0
    - databricks-cli==0.17.4
    - dfdb==0.0.1
    - distlib==0.3.6
    - distributed==2022.8.0
    - docker==5.0.3
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - filelock==3.9.0
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - gurobipy==10.0.0
    - gym==0.21.0
    - heapdict==1.0.1
    - humanfriendly==10.0
    - hydra-core==1.2.0
    - idna==3.4
    - importlib-metadata==5.2.0
    - importlib-resources==5.10.2
    - iniconfig==2.0.0
    - isodate==0.6.1
    - jeepney==0.8.0
    - jinja2==3.1.2
    - jmespath==1.0.0
    - joblib==1.2.0
    - jsonpickle==2.2.0
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - knack==0.9.0
    - lightgbm==3.3.2
    - llvmlite==0.39.1
    - locket==1.0.0
    - mako==1.2.4
    - markdown==3.4.1
    - markupsafe==2.1.2
    - matplotlib==3.5.2
    - mlflow-skinny==2.1.1
    - msal==1.20.0
    - msal-extensions==0.3.1
    - msgpack==1.0.4
    - msrest==0.7.1
    - msrestazure==0.6.4
    - multidict==6.0.4
    - ndg-httpsclient==0.5.1
    - networkx==2.8.5
    - numba==0.56.0
    - numpy==1.22.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - ortools==9.3.10497
    - packaging==21.3
    - pandas==1.5.3
    - paramiko==2.12.0
    - partd==1.3.0
    - pathspec==0.10.3
    - pathtools==0.1.2
    - pillow==9.4.0
    - pkginfo==1.9.6
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.6.2
    - pluggy==1.0.0
    - portalocker==2.7.0
    - promise==2.3
    - protobuf==3.20.3
    - psutil==5.9.4
    - psycopg2-binary==2.9.3
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydantic==1.9.1
    - pydeprecate==0.3.2
    - pygments==2.14.0
    - pyjwt==2.6.0
    - pynacl==1.5.0
    - pyopenssl==22.0.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pysocks==1.7.1
    - pytest==7.1.3
    - python-dateutil==2.8.2
    - python-dotenv==0.21.0
    - python-editor==1.0.4
    - pytorch-lightning==1.7.1
    - pytz==2022.7.1
    - pyyaml==6.0
    - ray==1.13.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - rsome==1.1.2
    - sb3-contrib==1.6.0
    - scikit-learn==1.2.0
    - scipy==1.10.0
    - seaborn==0.11.2
    - secretstorage==3.3.3
    - sentry-sdk==1.9.0
    - setproctitle==1.3.2
    - shellingham==1.5.0.post1
    - shortuuid==1.0.11
    - six==1.16.0
    - sklearn==0.0
    - smmap==5.0.0
    - sortedcontainers==2.4.0
    - sqlalchemy==1.3.19
    - sqlalchemy-utils==0.36.8
    - sqlparse==0.4.3
    - stable-baselines3==1.6.0
    - tabulate==0.9.0
    - tblib==1.7.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==1.13.1
    - torchmetrics==0.11.0
    - tornado==6.1
    - tqdm==4.64.1
    - typer==0.3.2
    - typer-cli==0.0.12
    - typing-extensions==4.4.0
    - urllib3==1.26.9
    - virtualenv==20.17.1
    - wandb==0.13.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - windpowerlib==0.2.1
    - xyzservices==2022.9.0
    - yarl==1.8.2
    - zict==2.2.0
    - zipp==3.11.0
